# Generated by Django 6.0.2 on 2026-02-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('perfil', '0003_rename_user_perfil_usuario_perfil_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='perfil.perfil'),
        ),
    ]
